spring.application.name=payment-service
server.port=8085

#
# JDBC Properties
#
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

#
# Additional Hibernate Properties
#
spring.jpa.hibernate.ddl-auto=update

#
# SSL Bundle Properties
#
spring.ssl.bundle.pem.payment-service-server.keystore.certificate=classpath:certificates/server-payment.pem
spring.ssl.bundle.pem.payment-service-server.keystore.private-key=classpath:certificates/server-payment-key.pem
spring.ssl.bundle.pem.payment-service-server.truststore.certificate=classpath:certificates/ca-cert.pem

#
# gRPC Server Properties
#
spring.grpc.server.port=7071
spring.grpc.server.ssl.enabled=true
spring.grpc.server.ssl.bundle=payment-service-server
spring.grpc.server.ssl.client-auth=require
