spring.application.name=order-service
server.port=8080

#
# JDBC Properties
#
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

#
# Additional Hibernate Properties
#
spring.jpa.hibernate.ddl-auto=update

#
# Properties for connecting to External Services
#
payment-service.base_url=http://localhost:8081

#
# Kafka Properties
#
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages='*'

order.kafka.topics=orders.events
delivery.kafka.topic.delivery-assigned=delivery.events
